-- 1. Create the "items" table
CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  contact TEXT NOT NULL,
  media_urls TEXT[] DEFAULT '{}',
  status TEXT DEFAULT 'LOST' CHECK (status IN ('LOST', 'FOUND', 'CLAIMED')),
  location TEXT,
  reporter_name TEXT,
  reporter_roll TEXT,
  reporter_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE items ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to read items
CREATE POLICY "Public items are viewable by everyone" ON items
  FOR SELECT USING (true);

-- 4. Create a policy to allow anyone to insert items (for this simple project)
-- Note: In a production app, you'd restrict this to authenticated users.
CREATE POLICY "Anyone can insert items" ON items
  FOR INSERT WITH CHECK (true);

-- 5. Create a policy to allow anyone to update items (to mark as claimed)
CREATE POLICY "Anyone can update items" ON items
  FOR UPDATE USING (true);

-- 6. Setup Storage for Images
-- First, go to the Supabase Dashboard > Storage and create a bucket named "item-images"
-- Then run these policies to allow public access:

-- Allow public access to images
-- CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'item-images' );
-- CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'item-images' );
